
# A newer version should be fine
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    branch = "master",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")
dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
	"nuget_package"
)

dotnet_register_toolchains()
dotnet_repositories_nugets()


git_repository(
	name = "d2l_rules_csharp",
	remote = "https://github.com/Brightspace/rules_csharp.git",
	branch = "master",
)

load(
    "@d2l_rules_csharp//csharp:defs.bzl",
    "csharp_register_toolchains",
    "csharp_repositories",
	
)

csharp_register_toolchains()
csharp_repositories()

### Generated by the tool
nuget_package(
    name = "newtonsoft.json",
    package = "newtonsoft.json",
    version = "13.0.1",
    sha256 = "2b6b52556e27e1b7913f33eedeb95568110c746bd64afff74357f1683878323a",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "netcoreapp2.2": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "netcoreapp3.0": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "netcoreapp3.1": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "net5.0": "lib/netstandard2.0/Newtonsoft.Json.dll",
        "net6.0": "lib/netstandard2.0/Newtonsoft.Json.dll",
    },
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "netcoreapp2.2": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "net5.0": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
        "net6.0": [
           "lib/netstandard2.0/Newtonsoft.Json.dll",
           "lib/netstandard2.0/Newtonsoft.Json.xml",
        ],
    },
)
### End of generated by the tool

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
