load(
    "@d2l_rules_csharp//csharp:defs.bzl",
    "csharp_binary",
    "csharp_library",
)

csharp_binary(
	name = "ConsoleApplication1",
	srcs = ["Program.cs" , "Helper.cs"],
	target_frameworks = ["net48"],
	out = "ConsoleApplication1"
)